#!/bin/sh -

# Tip to use shell
true ,/^; exec awk -f "$0" -v mainFile="$0" -- "$@"; exit #/ {}

BEGIN {
  # We define verbode mode here
  verbose = 0;

  # We are includeing script files
  include("./lib/check.awk");
  include("./lib/common.awk");
  include("./command/init.awk");
  sourceIncludes();

  # Check configuration and required executables
  checkConfiguration();
  checkExecs();

  # Main command parameters handler
  if (ARGC == 1) {
    usage();
  } else {
    for (i = 1; i < ARGC; i++) {
      argument = ARGV[i];
      # Options
      if (argument ~ "^(-v|--version)$") {
        print(version);
        exit;
      } else if (argument ~ "^(-V|--verbose)$") {
        verbose = 1;
      } else if (argument ~ "^(-h|--help)?$"){
        usage();
      }
      # Commands
      else if (argument == "check") {
        verbose = 1;
        checkConfiguration();
        checkExecs();
        exit;
      } else if (argument == "init") {
        # todo
      }
      # If there is some trouble with the command/options
      else {
        printf("\nCommand \"%s\" is not defined.\n", argument);
        usage();
      }
    }
  }
  exit;
}

# function to incldue files
function include(includeFile) {
  includes[includeFile]
}

# Function to build execution string to require
function sourceIncludes() {
  if (!loaded) {
    "which awk" | getline awkPath
    scriptname = awkPath " -f "mainFile;

    for (i = 1; i < ARGC; i++) {
      args = args " "ARGV[i];
    }
    for (file in includes) {
      includeString = includeString " -f "file;
    }
    cmd = sprintf("%s %s -v loaded=1 -- %s\n", scriptname, includeString, args);
    system(cmd);
    exit;
  }
}
